### ISSUE TITLE
404 for http://kaberc.ru/kreskin_bd

### ISSUE THREAD

**Issue by DashaSerdyuk** [kaberc/kaberc.github.io#1]
Hi! Can't open http://kaberc.ru/kreskin_bd, 404. No VPN. The same page (30 april) but for other boy opened successfully. 
Chrome version: Version 80.0.3987.122 (Official Build) (64-bit), OS Ubuntu 16.04.6 LTS

**Comment by kaberc** [comment]
Sorry, cannot reproduce. Have a good day!
